services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dds-price-provider
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    network_mode: host
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml:ro
      - ./resources:/app/resources:ro
